version: '3.8'
services:
  mongodb:
    build: .
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=CompassCine

volumes:
  mongo_data: